default:
	gcc -Wall addition.c division.c multiplication.c subtraction.c main.c -o calculator

clean:
	rm -f calculator && gcc -Wall addition.c division.c multiplication.c subtraction.c main.c -o calculator

